### ISSUE TITLE
Please use only whitelisted stuff, otherwise this is unusable

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP-samples/abap-file-uploader#1]
https://blogs.sap.com/wp-content/uploads/2020/06/2020-06-20_13h53_50.png
Use of Class CL_XCO_ASQL_CONSTRAINT_FACTORY is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 38	ABAP Activation Problem
Use of Class CL_XCO_ASQL_CONSTRAINT_FACTORY is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 38	ABAP Activation Problem
Use of Class XCO_CP_ABAP is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 40	ABAP Activation Problem
Use of Class XCO_CP_ABAP is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 40	ABAP Activation Problem
Use of Class XCO_CP_ABAP is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 40	ABAP Activation Problem
Use of Class XCO_CP_ABAP_REPOSITORY is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 37	ABAP Activation Problem
Use of Class XCO_CP_ABAP_REPOSITORY is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 37	ABAP Activation Problem
Use of Interface IF_XCO_AD_TABLE is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 44	ABAP Activation Problem
Use of Interface IF_XCO_AR_TABL_API_OBJECT is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 89	ABAP Activation Problem
Use of Interface IF_XCO_AR_TABL_API_OBJECT is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 89	ABAP Activation Problem
Use of Interface IF_XCO_AR_TABL_API_OBJECT is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 89	ABAP Activation Problem
Use of Interface IF_XCO_CP_AR_API_OBJECTS is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 39	ABAP Activation Problem
Use of Interface IF_XCO_CP_AR_API_OBJECTS is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 39	ABAP Activation Problem
Use of Interface IF_XCO_DATABASE_TABLE is not permitted.	zcl_abap_file_uploader.aclass	/NSC_EN/.adt/classlib/classes/zcl_abap_file_uploader/zcl_abap_file_uploader.aclass	line 90	ABAP Activation Problem

**Comment by jung-thomas** [comment]
What kind of system and release are you trying this one?  This sample is for the ABAP runtime in SAP Cloud Platform.  An on premise version of HANA will not contain the XCO APIs yet.

**Comment by DerGuteWolf** [comment]
This an ABAP Environment in our PartnerEdge Account! And please note the error is not that the classes are not there but that their usage is not permitted.
System Info:
![image](https://user-images.githubusercontent.com/638512/85201476-de0cb200-b2ff-11ea-872f-80eff26e2e57.png)

**Comment by jung-thomas** [comment]
The XCO APIs are available automatically in trial systems.  In productive accounts it says:  "The XCO library is currently only available via feature toggle. If you are interested in using this new feature, please contact SAP." https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html 

For more general information on XCO:
https://blogs.sap.com/2020/05/17/the-rap-generator

https://blogs.sap.com/2020/05/18/xco-a-powerful-abap-re-use-library-now-available-in-abap-for-key-users/

**Comment by DerGuteWolf** [comment]
Could you mention this in the README?

**Comment by jung-thomas** [comment]
I have already added it.

**Comment by DerGuteWolf** [comment]
Thanks for the quick response! I will try to get them activated in our instance....
